-- 环保小脑（enviro-brain）PostgreSQL 建表脚本
-- 目标库：smartpark_scenes_zhh（连接串已指定库名，无需 CREATE DATABASE）
-- 由 MySQL 5.7 方言迁移而来；差异点：
--   AUTO_INCREMENT        -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   tinyint(1) 标志位      -> SMALLINT（对应 Java Integer）
--   datetime              -> TIMESTAMP
--   ENGINE/CHARSET/反引号  -> 去除
--   ON UPDATE CURRENT_TIMESTAMP -> 由 set_updated_at() 触发器维护
--   inline KEY idx_...    -> 独立 CREATE INDEX

-- ──────────────────────────────────────────────
-- 巡检记录主表
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inspection_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        VARCHAR(64)  NOT NULL,
    inspection_date DATE         NOT NULL,
    total_cameras   INT          NOT NULL DEFAULT 0,
    online_count    INT          NOT NULL DEFAULT 0,
    offline_count   INT          NOT NULL DEFAULT 0,
    abnormal_count  INT          NOT NULL DEFAULT 0,
    status          VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',
    sync_version    BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_inspection_records_batch_id ON inspection_records (batch_id);
CREATE INDEX IF NOT EXISTS idx_inspection_records_date ON inspection_records (inspection_date);
CREATE INDEX IF NOT EXISTS idx_inspection_records_sync_version ON inspection_records (sync_version);

-- ──────────────────────────────────────────────
-- 摄像头配置表
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS camera_config (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_code      VARCHAR(64)  NOT NULL,
    camera_name      VARCHAR(128) NOT NULL,
    enterprise       VARCHAR(256),
    artemis_device_id VARCHAR(128),
    rtsp_url         VARCHAR(512),
    location         VARCHAR(256),
    enabled          SMALLINT     NOT NULL DEFAULT 1,
    ledger_enabled   SMALLINT     NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_camera_config_camera_code ON camera_config (camera_code);

-- ──────────────────────────────────────────────
-- 摄像头巡检结果表
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS camera_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id     BIGINT       NOT NULL,
    camera_code   VARCHAR(64)  NOT NULL,
    camera_name   VARCHAR(128),
    status        VARCHAR(20)  NOT NULL,
    quality_score NUMERIC(5,2),
    screenshot_path VARCHAR(512),
    error_message VARCHAR(512),
    sync_version  BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_camera_results_record FOREIGN KEY (record_id) REFERENCES inspection_records (id)
);
CREATE INDEX IF NOT EXISTS idx_camera_results_record_id ON camera_results (record_id);
CREATE INDEX IF NOT EXISTS idx_camera_results_camera_code ON camera_results (camera_code);
CREATE INDEX IF NOT EXISTS idx_camera_results_status ON camera_results (status);
CREATE INDEX IF NOT EXISTS idx_camera_results_sync_version ON camera_results (sync_version);

-- ──────────────────────────────────────────────
-- 巡查台账记录表
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ledger_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id     BIGINT       NOT NULL,
    inspection_date DATE        NOT NULL,
    content       TEXT,
    docx_path     VARCHAR(512),
    sync_version  BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ledger_records_record FOREIGN KEY (record_id) REFERENCES inspection_records (id)
);
CREATE INDEX IF NOT EXISTS idx_ledger_records_record_id ON ledger_records (record_id);
CREATE INDEX IF NOT EXISTS idx_ledger_records_date ON ledger_records (inspection_date);
CREATE INDEX IF NOT EXISTS idx_ledger_records_sync_version ON ledger_records (sync_version);

-- ──────────────────────────────────────────────
-- 全局同步版本序列
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sync_version_seq (
    id         INT       NOT NULL DEFAULT 1 PRIMARY KEY,
    next_val   BIGINT    NOT NULL DEFAULT 1,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sync_version_seq (id, next_val, updated_at) VALUES (1, 1, CURRENT_TIMESTAMP)
    ON CONFLICT (id) DO NOTHING;

-- ──────────────────────────────────────────────
-- updated_at 自动维护触发器
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inspection_records_updated_at ON inspection_records;
CREATE TRIGGER trg_inspection_records_updated_at
    BEFORE UPDATE ON inspection_records
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_camera_config_updated_at ON camera_config;
CREATE TRIGGER trg_camera_config_updated_at
    BEFORE UPDATE ON camera_config
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_ledger_records_updated_at ON ledger_records;
CREATE TRIGGER trg_ledger_records_updated_at
    BEFORE UPDATE ON ledger_records
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sync_version_seq_updated_at ON sync_version_seq;
CREATE TRIGGER trg_sync_version_seq_updated_at
    BEFORE UPDATE ON sync_version_seq
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
